name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Install express
        run: npm install express

      - name: Run OG Image Server Script
        run: node scripts/og-image-server.js a06e7d9232deeae1a0e99c6ac65cc3046bd92613 d92c7d87266ff576a550588f58744a3e361bd57f
